CMakeLists.txt
README.md
include/xc_shell.h
src/main.cc
src/xc_shell.cc

See https://github.com/superxcgm/xcShell/issues/6

Chain three parts together.

---

auto/run.sh
include/placeholder.h
include/xc_shell.h
main.cpp
src/main.cc
src/placeholder.cc
src/xc_shell.cc
test/placeholder_test.cc
test/xc_shell_test.cc

See https://github.com/superxcgm/xcShell/issues/8

Read user input and echo

---

include/xc_shell.h
include/xc_utils.h
src/xc_shell.cc
src/xc_utils.cc
test/xc_shell_test.cc
test/xc_utils_test.cc

See https://github.com/superxcgm/xcShell/issues/9

Split user input line to command and args

---

auto/install.sh
include/command_executor.h
include/xc_error.h
include/xc_shell.h
src/command_executor.cc
src/main.cc
src/xc_shell.cc
test/xc_shell_test.cc

See https://github.com/superxcgm/xcShell/issues/10

Execute command by fork/exec

---

include/command_executor.h
src/command_executor.cc
test/xc_shell_test.cc

See https://github.com/superxcgm/xcShell/issues/18

Add support for cd

---

include/xc_shell.h
include/xc_utils.h
src/command_executor.cc
src/main.cc
src/xc_shell.cc
src/xc_utils.cc
test/xc_utils_test.cc

See https://github.com/superxcgm/xcShell/issues/12

Prompt display current dir

---

include/xcshell/build_in/alias.h
include/xcshell/build_in/build_in.h
include/xcshell/command_executor.h
include/xcshell/shell.h
include/xcshell/utils.h
src/build_in/alias.cc
src/build_in/build_in.cc
src/command_executor.cc
src/shell.cc
src/utils.cc
test/build_in/alias_test.cc
test/utils_test.cc

See https://github.com/superxcgm/xcShell/issues/28

shell can auto replace command using alias

---

include/xcshell/build_in/alias.h
src/build_in/alias.cc
test/build_in/alias_test.cc

See https://github.com/superxcgm/xcShell/issues/28

Alias can replace many times

---

CMakeLists.txt
src/build_in/alias.cc
src/build_in/build_in.cc
src/build_in/cd.cc
src/command_executor.cc
src/main.cc
src/shell.cc
src/utils.cc

See https://github.com/superxcgm/xcShell/issues/37

Add include dir to cmake

---

CMakeLists.txt
auto/build.sh
auto/run.sh
auto/test.sh
src/command_executor.cc
src/shell.cc
src/utils.cc

See https://github.com/superxcgm/xcShell/issues/41

Fix compile error in Ubuntu 20.04

---

.github/workflows/ci.yml

See https://github.com/superxcgm/xcShell/issues/41

Add ubuntu 20.04 build in pipeline

---

include/xcshell/build_in/alias.h
include/xcshell/build_in/build_in.h
include/xcshell/build_in/cd.h
include/xcshell/command_executor.h
include/xcshell/shell.h
include/xcshell/utils.h
src/command_executor.cc
src/shell.cc

See https://github.com/superxcgm/xcShell/issues/44

Ignore SIGINT in shell

---

include/xcshell/command_executor.h
include/xcshell/constants.h
include/xcshell/parser.h
include/xcshell/utils.h
src/build_in/build_in.cc
src/command_executor.cc
src/parser.cc
src/shell.cc
src/utils.cc
test/parser_test.cc
test/utils_test.cc

see https://github.com/superxcgm/xcShell/issues/42

Single pipe | Redierct 

---

.github/workflows/ci.yml
include/xcshell/command_executor.h
src/build_in/build_in.cc
src/command_executor.cc
src/shell.cc
src/utils.cc
test/build_in/alias_test.cc
test/parser_test.cc
test/test_main.cc
test/utils_test.cc

see https://github.com/superxcgm/xcShell/issues/53

Multi pipe | Redierct

---

CMakeLists.txt
conanfile.txt
include/xcshell/command_executor.h
include/xcshell/shell.h
src/command_executor.cc
src/shell.cc

See https://github.com/superxcgm/xcShell/issues/65

Integrate spdlog

---

include/xcshell/command_executor.h
include/xcshell/utils.h
src/build_in/cd.cc
src/command_executor.cc
src/parser.cc
src/shell.cc
src/utils.cc
test/utils_test.cc

See https://github.com/superxcgm/xcShell/issues/54

Refactor and bug fix

---

README.md
include/xcshell/build_in/alias.h
include/xcshell/build_in/build_in.h
include/xcshell/build_in/build_in_command.h
include/xcshell/build_in/cd.h
include/xcshell/build_in/j.h
sonar-project.properties
src/build_in/alias.cc
src/error_handling.cc
src/shell.cc

See https://github.com/superxcgm/xcShell/issues/84

Add cfamily options and fix code smell

---

CPPLINT.cfg
include/xcshell/build_in/build_in.h
include/xcshell/command_executor.h
include/xcshell/parser.h
include/xcshell/utils.h
src/build_in/build_in.cc
src/build_in/cd.cc
src/build_in/j.cc
src/command_executor.cc
src/parser.cc
src/shell.cc
src/utils.cc

See https://github.com/superxcgm/xcShell/issues/84

Code Smell Fix

---

include/xcshell/build_in/alias.h
include/xcshell/command_executor.h
include/xcshell/error_handling.h
include/xcshell/parser.h
include/xcshell/shell.h
include/xcshell/utils.h
src/build_in/alias.cc
src/command_executor.cc
src/error_handling.cc
src/main.cc
src/parser.cc
src/shell.cc
src/utils.cc

See https://github.com/superxcgm/xcShell/issues/84

Fix Code Smell

---

CMakeLists.txt
auto/functional_test.sh
auto/install.sh
auto/run.sh
src/CMakeLists.txt
src/main.cc
src/shell.cc
test/CMakeLists.txt

See https://github.com/superxcgm/xcShell/issues/46

Refactor cmake script & add install instruction

---

auto/data/str_quote.functional_test.expected.out
auto/data/str_quote.functional_test.in
src/parser.cc
test/parser_test.cc

see https://github.com/superxcgm/xcShell/issues/80

double quotation mark can parse correctly

---

src/parser.cc
test/parser_test.cc

See https://github.com/superxcgm/xcShell/issues/80

Fix merge error
